#!/usr/bin/env python3

import sys
import re

global_lut = {}
'''
Map each variable to its value
'''

reverse_lut = {}
'''
Map each variable contained in expressions to
the list of variables it belongs
'''

var_regexp = re.compile(r'\${(?P<var>[^}{]+)}')
subst_regexp = re.compile(r'@(?P<var>[^@]+)@')

it = '#__TOKEN_TO_REPLACE__#'


def unquote(s):
    '''
    Unquote the string
    '''
    if s.startswith("'") and s.endswith("'"):
        return s[1:-1]
    if s.startswith('"') and s.endswith('"'):
        return s[1:-1]
    return s


def fill_reverse_table(identifier, value):
    '''
    Add an entry in the reverse lookup table 
    for each variable in the identifier expression
    '''
    for var in var_regexp.findall(value):
        reverse_lut[var] = reverse_lut.get(var, []) + [identifier]


def build_global_table(config):
    '''
    Build the mapping between variables
    and their expression
    '''
    with open(config, 'r', encoding='utf-8') as fi:
        for line in fi:
            if '=' in line:
                line_spl = line.strip().split('=')
                identifer = line_spl[0]
                value = ''.join(line_spl[1:])
                if identifer.isidentifier():
                    global_lut[identifer] = unquote(value)
                    fill_reverse_table(identifer, value)


def recursive_expansion():
    '''
    Recursively expand variable until all variables are expanded
    '''
    to_replace = set(reverse_lut)
    while to_replace:
        to_subst = to_replace.pop()
        variables = reverse_lut[to_subst]
        for variable in variables:
            expr = global_lut[variable]
            if to_subst not in global_lut:
                continue
            global_lut[variable] = expr.replace(
                f'${{{to_subst}}}', global_lut[to_subst])
            fill_reverse_table(variable, global_lut[variable])


def replace(input_filename, output_filename):
    '''
    Expand the variable @<var>@ by global_lut[<var>] (i.e. ${var})
    '''
    with open(input_filename, 'r', encoding='utf-8') as fi:
        with open(output_filename, 'w', encoding='utf-8') as fo:
            for line in fi:
                matches = subst_regexp.findall(line)
                if matches != []:
                    for match in matches:
                        line = line.replace(
                            f'@{match}@', global_lut[match.lower()])
                fo.write(line)


def main():
    config_logfile = sys.argv[1]
    input_filename = sys.argv[2]
    output_filename = sys.argv[3]
    build_global_table(config_logfile)
    recursive_expansion()
    replace(input_filename, output_filename)


if __name__ == '__main__':
    main()
